lane :bonjour do

  UI.success "Bravo !!"

  scan(
    project: "FastlaneDemo.xcodeproj",
    code_coverage:true
  )
xcov

end

lane:deploy do

  version = get_version_number()
  print version
  
end
